version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    depends_on:
      - frontend
    networks:
      - sail

  frontend:
    image: "node"
    volumes:
      - "./frontend:/var/www/html"
    working_dir: "/var/www/html"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "${BACKEND_URL}"
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - sail

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
